var _HTbinan, _Vbinan, _D, _PT;
var _Vtk;

var canvas = document.getElementById('myCanvas');
    var ctx = canvas.getContext('2d');
    let radius = canvas.width/2;
    ctx.translate(radius, radius);
    ctx.beginPath();
    ctx.strokeStyle = 'green';
    ctx.moveTo(0,radius/27);
    ctx.lineTo(0,-radius/27); 
    ctx.stroke();
    ctx.beginPath();
    ctx.strokeStyle = 'green';
    ctx.moveTo(radius/27,0);
    ctx.lineTo(-radius/27,0); 
    ctx.stroke();
    ctx.beginPath ();
    ctx.arc(0, 0, radius, 0, 2*Math.PI); 
    ctx.strokeStyle = 'green'; 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 5/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 1/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 9/10*radius, 0, 2*Math.PI); 
    ctx.setLineDash([2,3]);
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 8/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 7/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 6/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 4/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 3/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5; 
    ctx.stroke();

    ctx.beginPath ();
    ctx.arc(0, 0, 2/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.getLineDash();
    ctx.beginPath ();
    ctx.arc(0, 0, 1/10*radius, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.getLineDash();
    ctx.beginPath ();
    ctx.arc(0, 0,radius + radius/10, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.getLineDash();
    ctx.beginPath ();
    ctx.arc(0, 0,radius + radius/5, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.getLineDash();
    ctx.beginPath ();
    ctx.arc(0, 0,radius + 3*radius/10, 0, 2*Math.PI); 
    ctx.lineWidth = 0.5;
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(0,radius/10);
    ctx.lineTo(0, radius); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10,0);
    ctx.lineTo(radius, 0); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10,0);
    ctx.lineTo(-radius,0); 
    ctx.stroke();  
    ctx.beginPath();
    ctx.moveTo(0,-radius/10);
    ctx.lineTo(0,-radius); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/18),radius/10*Math.sin(Math.PI/18));
    ctx.lineTo(radius, radius*Math.tan(Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/9),radius/10*Math.sin(Math.PI/9));
    ctx.lineTo(radius, radius*Math.tan(Math.PI/9)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/6),radius/10*Math.sin(Math.PI/6));
    ctx.lineTo(radius,radius*Math.tan(Math.PI/6)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(2*Math.PI/9),radius/10*Math.sin(2*Math.PI/9));
    ctx.lineTo(radius,radius*Math.tan(2*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(5*Math.PI/18),radius/10*Math.sin(5*Math.PI/18));
    ctx.lineTo(radius,radius*Math.tan(5*Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/3),radius/10*Math.sin(Math.PI/3));
    ctx.lineTo(radius,radius*Math.tan(Math.PI/3)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(7*Math.PI/18),radius/10*Math.sin(7*Math.PI/18));
    ctx.lineTo(radius,radius*Math.tan(7*Math.PI/18)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(4*Math.PI/9),radius/10*Math.sin(4*Math.PI/9));
    ctx.lineTo(radius,radius*Math.tan(4*Math.PI/9)); 
    ctx.stroke();  
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/18),-radius/10*Math.sin(Math.PI/18));
    ctx.lineTo(radius, -radius*Math.tan(Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/9),-radius/10*Math.sin(Math.PI/9));
    ctx.lineTo(radius, -radius*Math.tan(Math.PI/9)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/6),-radius/10*Math.sin(Math.PI/6));
    ctx.lineTo(radius,-radius*Math.tan(Math.PI/6)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(2*Math.PI/9),-radius/10*Math.sin(2*Math.PI/9));
    ctx.lineTo(radius,-radius*Math.tan(2*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(5*Math.PI/18),-radius/10*Math.sin(5*Math.PI/18));
    ctx.lineTo(radius,-radius*Math.tan(5*Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(Math.PI/3),-radius/10*Math.sin(Math.PI/3));
    ctx.lineTo(radius,-radius*Math.tan(Math.PI/3)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(7*Math.PI/18),-radius/10*Math.sin(7*Math.PI/18));
    ctx.lineTo(radius,-radius*Math.tan(7*Math.PI/18)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(4*Math.PI/9),-radius/10*Math.sin(4*Math.PI/9));
    ctx.lineTo(radius,-radius*Math.tan(4*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/18),-radius/10*Math.sin(Math.PI/18));
    ctx.lineTo(-radius, -radius*Math.tan(Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/9),-radius/10*Math.sin(Math.PI/9));
    ctx.lineTo(-radius, -radius*Math.tan(Math.PI/9)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/6),-radius/10*Math.sin(Math.PI/6));
    ctx.lineTo(-radius,-radius*Math.tan(Math.PI/6)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(2*Math.PI/9),-radius/10*Math.sin(2*Math.PI/9));
    ctx.lineTo(-radius,-radius*Math.tan(2*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(5*Math.PI/18),-radius/10*Math.sin(5*Math.PI/18));
    ctx.lineTo(-radius,-radius*Math.tan(5*Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/3),-radius/10*Math.sin(Math.PI/3));
    ctx.lineTo(-radius,-radius*Math.tan(Math.PI/3)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(7*Math.PI/18),-radius/10*Math.sin(7*Math.PI/18));
    ctx.lineTo(-radius,-radius*Math.tan(7*Math.PI/18)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(4*Math.PI/9),-radius/10*Math.sin(4*Math.PI/9));
    ctx.lineTo(-radius,-radius*Math.tan(4*Math.PI/9)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/18),radius/10*Math.sin(Math.PI/18));
    ctx.lineTo(-radius, radius*Math.tan(Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/9),radius/10*Math.sin(Math.PI/9));
    ctx.lineTo(-radius, radius*Math.tan(Math.PI/9)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/6),radius/10*Math.sin(Math.PI/6));
    ctx.lineTo(-radius,radius*Math.tan(Math.PI/6)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(2*Math.PI/9),radius/10*Math.sin(2*Math.PI/9));
    ctx.lineTo(-radius,radius*Math.tan(2*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(5*Math.PI/18),radius/10*Math.sin(5*Math.PI/18));
    ctx.lineTo(-radius,radius*Math.tan(5*Math.PI/18)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(Math.PI/3),radius/10*Math.sin(Math.PI/3));
    ctx.lineTo(-radius,radius*Math.tan(Math.PI/3)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(7*Math.PI/18),radius/10*Math.sin(7*Math.PI/18));
    ctx.lineTo(-radius,radius*Math.tan(7*Math.PI/18)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(4*Math.PI/9),radius/10*Math.sin(4*Math.PI/9));
    ctx.lineTo(-radius,radius*Math.tan(4*Math.PI/9)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(5*Math.PI/180),radius/10*Math.sin(5*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(5*Math.PI/180)); 
    ctx.setLineDash([10,radius/10]);
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(15*Math.PI/180),radius/10*Math.sin(15*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(15*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(25*Math.PI/180),radius/10*Math.sin(25*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(25*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(35*Math.PI/180),radius/10*Math.sin(35*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(35*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(45*Math.PI/180),radius/10*Math.sin(45*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(45*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(55*Math.PI/180),radius/10*Math.sin(55*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(55*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(65*Math.PI/180),radius/10*Math.sin(65*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(65*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(75*Math.PI/180),radius/10*Math.sin(75*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(75*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(85*Math.PI/180),radius/10*Math.sin(85*Math.PI/180));
    ctx.lineTo(radius, radius*Math.tan(85*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(5*Math.PI/180),-radius/10*Math.sin(5*Math.PI/180));
    ctx.lineTo(radius, -radius*Math.tan(5*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(15*Math.PI/180),-radius/10*Math.sin(15*Math.PI/180));
    ctx.lineTo(radius, -radius*Math.tan(15*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(25*Math.PI/180),-radius/10*Math.sin(25*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(25*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(35*Math.PI/180),-radius/10*Math.sin(35*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(35*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(45*Math.PI/180),-radius/10*Math.sin(45*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(45*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(55*Math.PI/180),-radius/10*Math.sin(55*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(55*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(65*Math.PI/180),-radius/10*Math.sin(65*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(65*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(75*Math.PI/180),-radius/10*Math.sin(75*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(75*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(radius/10*Math.cos(85*Math.PI/180),-radius/10*Math.sin(85*Math.PI/180));
    ctx.lineTo(radius,-radius*Math.tan(85*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(5*Math.PI/180),-radius/10*Math.sin(5*Math.PI/180));
    ctx.lineTo(-radius, -radius*Math.tan(5*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(15*Math.PI/180),-radius/10*Math.sin(15*Math.PI/180));
    ctx.lineTo(-radius, -radius*Math.tan(15*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(25*Math.PI/180),-radius/10*Math.sin(25*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(25*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(35*Math.PI/180),-radius/10*Math.sin(35*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(35*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(45*Math.PI/180),-radius/10*Math.sin(45*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(45*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(55*Math.PI/180),-radius/10*Math.sin(55*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(55*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(65*Math.PI/180),-radius/10*Math.sin(65*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(65*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(75*Math.PI/180),-radius/10*Math.sin(75*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(75*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(85*Math.PI/180),-radius/10*Math.sin(85*Math.PI/180));
    ctx.lineTo(-radius,-radius*Math.tan(85*Math.PI/180)); 
    ctx.stroke();  
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(5*Math.PI/180),radius/10*Math.sin(5*Math.PI/180));
    ctx.lineTo(-radius, radius*Math.tan(5*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(15*Math.PI/180),radius/10*Math.sin(15*Math.PI/180));
    ctx.lineTo(-radius, radius*Math.tan(15*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(25*Math.PI/180),radius/10*Math.sin(25*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(25*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(35*Math.PI/180),radius/10*Math.sin(35*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(35*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(45*Math.PI/180),radius/10*Math.sin(45*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(45*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(55*Math.PI/180),radius/10*Math.sin(55*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(55*Math.PI/180)); 
    ctx.stroke(); 
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(65*Math.PI/180),radius/10*Math.sin(65*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(65*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(75*Math.PI/180),radius/10*Math.sin(75*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(75*Math.PI/180)); 
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(-radius/10*Math.cos(85*Math.PI/180),radius/10*Math.sin(85*Math.PI/180));
    ctx.lineTo(-radius,radius*Math.tan(85*Math.PI/180)); 
    ctx.stroke();
    ctx.font = '5pt Arial';
    ctx.fillStyle = 'rgb(5, 168, 40)';
    ctx.fillText("2", 2*radius/10+2,-2);
    ctx.fillText("3", 3*radius/10+2,-2);
    ctx.fillText("4", 4*radius/10+2,-2);
    ctx.fillText("5", 5*radius/10+2,-2);
    ctx.fillText("6", 6*radius/10+2,-2);
    ctx.fillText("7", 7*radius/10+2,-2);
    ctx.fillText("8", 8*radius/10+2,-2);
    ctx.fillText("9", 9*radius/10+2,-2);
    ctx.fillText("2", -radius/5-6,6);
    ctx.fillText("3", -3*radius/10-6,6);
    ctx.fillText("4", -4*radius/10-6,6);
    ctx.fillText("5", -5*radius/10-6,6);
    ctx.fillText("6", -6*radius/10-6,6);
    ctx.fillText("7", -7*radius/10-6,6);
    ctx.fillText("8", -8*radius/10-6,6);
    ctx.fillText("9", -9*radius/10-6,6);
    ctx.fillText("2", 2, 2*radius/10+6);
    ctx.fillText("3", 2, 3*radius/10+6);
    ctx.fillText("4", 2, 4*radius/10+6);
    ctx.fillText("5", 2, 5*radius/10+6);
    ctx.fillText("6", 2, 6*radius/10+6);
    ctx.fillText("7", 2, 7*radius/10+6);
    ctx.fillText("8", 2, 8*radius/10+6);
    ctx.fillText("9", 2, 9*radius/10+6);
    ctx.fillText("2", -5, -2*radius/10-2);
    ctx.fillText("3", -5, -3*radius/10-2);
    ctx.fillText("4", -5, -4*radius/10-2);
    ctx.fillText("5", -5, -5*radius/10-2);
    ctx.fillText("6", -5, -6*radius/10-2);
    ctx.fillText("7", -5, -7*radius/10-2);
    ctx.fillText("8", -5, -8*radius/10-2);
    ctx.fillText("9", -5, -9*radius/10-2);
    ctx.font = '6pt Arial';
    ctx.fillStyle = 'rgb(5, 168, 40)';
    ctx.fillText("180", -6, -radius+8);
    ctx.fillText("0", -2, radius-4);
    ctx.translate (-radius,0);
    ctx.rotate (3*Math.PI/2);
    ctx.fillText("90", -4,8);
    ctx.rotate (-3*Math.PI/2);
    ctx.translate (2*radius,0);
    ctx.rotate (Math.PI/2);
    ctx.fillText("270", -6,8);
    ctx.rotate (-Math.PI/2);
    ctx.translate (-radius,0);
    ctx.translate (radius*Math.cos(Math.PI/18), -radius*Math.sin(Math.PI/18));
    ctx.rotate(8*Math.PI/18);
    ctx.fillText("260",-6,7);
    ctx.fillText("80",-4,-3);
    ctx.rotate(-8*Math.PI/18);
    ctx.translate (-radius*Math.cos(Math.PI/18), radius*Math.sin(Math.PI/18));
    ctx.translate (radius*Math.cos(2*Math.PI/18), -radius*Math.sin(2*Math.PI/18));
    ctx.rotate(7*Math.PI/18);
    ctx.fillText("250",-6,7);
    ctx.fillText("70",-4,-3);
    ctx.rotate(-7*Math.PI/18);
    ctx.translate (-radius*Math.cos(2*Math.PI/18), radius*Math.sin(2*Math.PI/18));
    ctx.translate (radius*Math.cos(3*Math.PI/18), -radius*Math.sin(3*Math.PI/18));
    ctx.rotate(6*Math.PI/18);
    ctx.fillText("240",-6,7);
    ctx.fillText("60",-4,-3);
    ctx.rotate(-6*Math.PI/18);
    ctx.translate (-radius*Math.cos(3*Math.PI/18), radius*Math.sin(3*Math.PI/18));
    ctx.translate (radius*Math.cos(4*Math.PI/18), -radius*Math.sin(4*Math.PI/18));
    ctx.rotate(5*Math.PI/18);
    ctx.fillText("230",-6,7);
    ctx.fillText("50",-4,-3);
    ctx.rotate(-5*Math.PI/18);
    ctx.translate (-radius*Math.cos(4*Math.PI/18), radius*Math.sin(4*Math.PI/18));
    ctx.translate (radius*Math.cos(5*Math.PI/18), -radius*Math.sin(5*Math.PI/18));
    ctx.rotate(4*Math.PI/18);
    ctx.fillText("220",-6,7);
    ctx.fillText("40",-4,-3);
    ctx.rotate(-4*Math.PI/18);
    ctx.translate (-radius*Math.cos(5*Math.PI/18), radius*Math.sin(5*Math.PI/18));
    ctx.translate (radius*Math.cos(6*Math.PI/18), -radius*Math.sin(6*Math.PI/18));
    ctx.rotate(3*Math.PI/18);
    ctx.fillText("210",-6,7);
    ctx.fillText("30",-4,-3);
    ctx.rotate(-3*Math.PI/18);
    ctx.translate (-radius*Math.cos(6*Math.PI/18), radius*Math.sin(6*Math.PI/18));
    ctx.translate (radius*Math.cos(7*Math.PI/18), -radius*Math.sin(7*Math.PI/18));
    ctx.rotate(2*Math.PI/18);
    ctx.fillText("200",-6,7);
    ctx.fillText("20",-4,-3);
    ctx.rotate(-2*Math.PI/18);
    ctx.translate (-radius*Math.cos(7*Math.PI/18), radius*Math.sin(7*Math.PI/18));
    ctx.translate (radius*Math.cos(8*Math.PI/18), -radius*Math.sin(8*Math.PI/18));
    ctx.rotate(Math.PI/18);
    ctx.fillText("190",-6,7);
    ctx.fillText("10",-4,-3);
    ctx.rotate(-Math.PI/18);
    ctx.translate (-radius*Math.cos(8*Math.PI/18), radius*Math.sin(8*Math.PI/18));
    ctx.translate (-radius*Math.cos(Math.PI/18), -radius*Math.sin(Math.PI/18));
    ctx.rotate(-8*Math.PI/18);
    ctx.fillText("100",-6,7);
    ctx.fillText("280",-6,-3);
    ctx.rotate(8*Math.PI/18);
    ctx.translate (radius*Math.cos(Math.PI/18), radius*Math.sin(Math.PI/18));
    ctx.translate (-radius*Math.cos(2*Math.PI/18), -radius*Math.sin(2*Math.PI/18));
    ctx.rotate(-7*Math.PI/18);
    ctx.fillText("110",-6,7);
    ctx.fillText("290",-6,-3);
    ctx.rotate(7*Math.PI/18);
    ctx.translate (radius*Math.cos(2*Math.PI/18), radius*Math.sin(2*Math.PI/18));
    ctx.translate (-radius*Math.cos(3*Math.PI/18), -radius*Math.sin(3*Math.PI/18));
    ctx.rotate(-6*Math.PI/18);
    ctx.fillText("120",-6,7);
    ctx.fillText("300",-6,-3);
    ctx.rotate(6*Math.PI/18);
    ctx.translate (radius*Math.cos(3*Math.PI/18), radius*Math.sin(3*Math.PI/18));
    ctx.translate (-radius*Math.cos(4*Math.PI/18), -radius*Math.sin(4*Math.PI/18));
    ctx.rotate(-5*Math.PI/18);
    ctx.fillText("130",-6,7);
    ctx.fillText("310",-6,-3);
    ctx.rotate(5*Math.PI/18);
    ctx.translate (radius*Math.cos(4*Math.PI/18), radius*Math.sin(4*Math.PI/18));
    ctx.translate (-radius*Math.cos(5*Math.PI/18), -radius*Math.sin(5*Math.PI/18));
    ctx.rotate(-4*Math.PI/18);
    ctx.fillText("140",-6,7);
    ctx.fillText("320",-6,-3);
    ctx.rotate(4*Math.PI/18);
    ctx.translate (radius*Math.cos(5*Math.PI/18), radius*Math.sin(5*Math.PI/18));
    ctx.translate (-radius*Math.cos(6*Math.PI/18), -radius*Math.sin(6*Math.PI/18));
    ctx.rotate(-3*Math.PI/18);
    ctx.fillText("150",-6,7);
    ctx.fillText("330",-6,-3);
    ctx.rotate(3*Math.PI/18);
    ctx.translate (radius*Math.cos(6*Math.PI/18), radius*Math.sin(6*Math.PI/18));
    ctx.translate (-radius*Math.cos(7*Math.PI/18), -radius*Math.sin(7*Math.PI/18));
    ctx.rotate(-2*Math.PI/18);
    ctx.fillText("160",-6,7);
    ctx.fillText("340",-6,-3);
    ctx.rotate(2*Math.PI/18);
    ctx.translate (radius*Math.cos(7*Math.PI/18), radius*Math.sin(7*Math.PI/18));
    ctx.translate (-radius*Math.cos(8*Math.PI/18), -radius*Math.sin(8*Math.PI/18));
    ctx.rotate(-Math.PI/18);
    ctx.fillText("170",-6,7);
    ctx.fillText("350",-6,-3);
    ctx.rotate(Math.PI/18);
    ctx.translate (radius*Math.cos(8*Math.PI/18), radius*Math.sin(8*Math.PI/18));
    ctx.translate (radius*Math.cos(Math.PI/18), radius*Math.sin(Math.PI/18));
    ctx.rotate(-8*Math.PI/18);
    ctx.fillText("280",-7,-3);
    ctx.fillText("100",-7,7);
    ctx.rotate(8*Math.PI/18);
    ctx.translate (-radius*Math.cos(Math.PI/18),-radius*Math.sin(Math.PI/18));
    ctx.translate (radius*Math.cos(2*Math.PI/18), radius*Math.sin(2*Math.PI/18));
    ctx.rotate(-7*Math.PI/18);
    ctx.fillText("290",-7,-3);
    ctx.fillText("110",-7,7);
    ctx.rotate(7*Math.PI/18);
    ctx.translate (-radius*Math.cos(2*Math.PI/18),-radius*Math.sin(2*Math.PI/18));
    ctx.translate (radius*Math.cos(3*Math.PI/18), radius*Math.sin(3*Math.PI/18));
    ctx.rotate(-6*Math.PI/18);
    ctx.fillText("300",-7,-3);
    ctx.fillText("120",-7,7);
    ctx.rotate(6*Math.PI/18);
    ctx.translate (-radius*Math.cos(3*Math.PI/18),-radius*Math.sin(3*Math.PI/18));
    ctx.translate (radius*Math.cos(4*Math.PI/18), radius*Math.sin(4*Math.PI/18));
    ctx.rotate(-5*Math.PI/18);
    ctx.fillText("310",-7,-3);
    ctx.fillText("130",-7,7);
    ctx.rotate(5*Math.PI/18);
    ctx.translate (-radius*Math.cos(4*Math.PI/18),-radius*Math.sin(4*Math.PI/18));
    ctx.translate (radius*Math.cos(5*Math.PI/18), radius*Math.sin(5*Math.PI/18));
    ctx.rotate(-4*Math.PI/18);
    ctx.fillText("320",-7,-3);
    ctx.fillText("140",-7,7);
    ctx.rotate(4*Math.PI/18);
    ctx.translate (-radius*Math.cos(5*Math.PI/18),-radius*Math.sin(5*Math.PI/18));
    ctx.translate (radius*Math.cos(6*Math.PI/18), radius*Math.sin(6*Math.PI/18));
    ctx.rotate(-3*Math.PI/18);
    ctx.fillText("330",-7,-3);
    ctx.fillText("150",-7,7);
    ctx.rotate(3*Math.PI/18);
    ctx.translate (-radius*Math.cos(6*Math.PI/18),-radius*Math.sin(6*Math.PI/18));
    ctx.translate (radius*Math.cos(7*Math.PI/18), radius*Math.sin(7*Math.PI/18));
    ctx.rotate(-2*Math.PI/18);
    ctx.fillText("340",-7,-3);
    ctx.fillText("160",-7,7);
    ctx.rotate(2*Math.PI/18);
    ctx.translate (-radius*Math.cos(7*Math.PI/18),-radius*Math.sin(7*Math.PI/18));
    ctx.translate (radius*Math.cos(8*Math.PI/18), radius*Math.sin(8*Math.PI/18));
    ctx.rotate(-Math.PI/18);
    ctx.fillText("350",-7,-3);
    ctx.fillText("170",-7,7);
    ctx.rotate(Math.PI/18);
    ctx.translate (-radius*Math.cos(8*Math.PI/18),-radius*Math.sin(8*Math.PI/18));
    ctx.translate (-radius*Math.cos(Math.PI/18), radius*Math.sin(Math.PI/18));
    ctx.rotate(8*Math.PI/18);
    ctx.fillText("80",-4,-3);
    ctx.fillText("260",-7,7);
    ctx.rotate(-8*Math.PI/18);
    ctx.translate (radius*Math.cos(Math.PI/18),-radius*Math.sin(Math.PI/18));
    ctx.translate (-radius*Math.cos(2*Math.PI/18), radius*Math.sin(2*Math.PI/18));
    ctx.rotate(7*Math.PI/18);
    ctx.fillText("70",-4,-3);
    ctx.fillText("250",-7,7);
    ctx.rotate(-7*Math.PI/18);
    ctx.translate (radius*Math.cos(2*Math.PI/18),-radius*Math.sin(2*Math.PI/18));
    ctx.translate (-radius*Math.cos(3*Math.PI/18), radius*Math.sin(3*Math.PI/18));
    ctx.rotate(6*Math.PI/18);
    ctx.fillText("60",-4,-3);
    ctx.fillText("240",-7,7);
    ctx.rotate(-6*Math.PI/18);
    ctx.translate (radius*Math.cos(3*Math.PI/18),-radius*Math.sin(3*Math.PI/18));
    ctx.translate (-radius*Math.cos(4*Math.PI/18), radius*Math.sin(4*Math.PI/18));
    ctx.rotate(5*Math.PI/18);
    ctx.fillText("50",-4,-3);
    ctx.fillText("230",-7,7);
    ctx.rotate(-5*Math.PI/18);
    ctx.translate (radius*Math.cos(4*Math.PI/18),-radius*Math.sin(4*Math.PI/18));
    ctx.translate (-radius*Math.cos(5*Math.PI/18), radius*Math.sin(5*Math.PI/18));
    ctx.rotate(4*Math.PI/18);
    ctx.fillText("40",-4,-3);
    ctx.fillText("220",-7,7);
    ctx.rotate(-4*Math.PI/18);
    ctx.translate (radius*Math.cos(5*Math.PI/18),-radius*Math.sin(5*Math.PI/18));
    ctx.translate (-radius*Math.cos(6*Math.PI/18), radius*Math.sin(6*Math.PI/18));
    ctx.rotate(3*Math.PI/18);
    ctx.fillText("30",-4,-3);
    ctx.fillText("210",-7,7);
    ctx.rotate(-3*Math.PI/18);
    ctx.translate (radius*Math.cos(6*Math.PI/18),-radius*Math.sin(6*Math.PI/18));
    ctx.translate (-radius*Math.cos(7*Math.PI/18), radius*Math.sin(7*Math.PI/18));
    ctx.rotate(2*Math.PI/18);
    ctx.fillText("20",-4,-3);
    ctx.fillText("200",-7,7);
    ctx.rotate(-2*Math.PI/18);
    ctx.translate (radius*Math.cos(7*Math.PI/18),-radius*Math.sin(7*Math.PI/18));
    ctx.translate (-radius*Math.cos(8*Math.PI/18), radius*Math.sin(8*Math.PI/18));
    ctx.rotate(Math.PI/18);
    ctx.fillText("10",-4,-3);
    ctx.fillText("190",-7,7);
    ctx.rotate(-Math.PI/18);
    ctx.translate (radius*Math.cos(8*Math.PI/18),-radius*Math.sin(8*Math.PI/18));
    ctx.rotate(Math.PI);
    ctx.setLineDash([0,0]);              
function validate() {
    _HTbinan = document.forms["input_form"]["_HTbinan"].value;
    _Vbinan = document.forms["input_form"]["_Vbinan"].value;
    _D = document.forms["input_form"]["_D"].value;
    _PT = document.forms["input_form"]["_PT"].value;
    _Vtk = document.forms["input_form"]["_Vtk"].value;
    if(0>_HTbinan||_HTbinan>360){
        alert ('Lỗi nhập số liệu: Hướng đi trôi dạt tổng hợp phải có giá trị từ: 0÷360 (độ)! (0≤HT≤360)');
    } else if(0>_PT||_PT>360){
        alert ('Lỗi nhập số liệu: Phương vị phải có giá trị từ: 0÷360 (độ)! (0≤PT≤360)');
    } else if(_Vbinan <= 0 || _Vtk <= 0){
        alert ('Lỗi nhập số liệu: Vận tốc phải có giá trị dương! (V > 0)');
    } else if(_D <= 0 || _D > 100){
        alert ('Lỗi nhập số liệu: Khoảng cách phải có giá trị từ: 0÷100 (liên)! (0<D≤100)');
    }else {
    var heso_kc = radius/100;
    var _Vbinan_doi= _Vbinan/6;
    var _Vtk_doi= _Vtk/6;
    var heso_v = radius/10;
    var x_a = -_Vbinan_doi*heso_v*Math.sin(_HTbinan*Math.PI/180);
    var y_a = _Vbinan_doi*heso_v*Math.cos(_HTbinan*Math.PI/180);
    ctx.beginPath();
    ctx.strokeStyle='blue';
    ctx.moveTo(0,0);
    ctx.lineTo(x_a,y_a); 
    ctx.arc(x_a, y_a, 3, 0, 2*Math.PI);
    ctx.lineWidth= 1;
    ctx.stroke();
        
        var x_Mo = _D*heso_kc*Math.sin(_PT*Math.PI/180);
        var y_Mo = -_D*heso_kc*Math.cos(_PT*Math.PI/180);
        ctx.beginPath();
        ctx.strokeStyle='red';
        ctx.arc(x_Mo, y_Mo, 3, 0, 2*Math.PI);
        ctx.lineWidth= 1;
        ctx.stroke();
        ctx.beginPath();
        ctx.strokeStyle='black';
        ctx.moveTo (0,0);
        ctx.setLineDash ([2,3]);
        ctx.lineTo (x_Mo,y_Mo);
        ctx.lineWidth= 1;
        ctx.stroke(); 
        ctx.setLineDash([0,0]);
        ctx.beginPath();
        ctx.strokeStyle = 'red';
        ctx.arc(0,0, _Vtk_doi*heso_v, 0 , 2*Math.PI);
        ctx.getElementById = 5;
        ctx.stroke();
        var x_MoKo= x_Mo - 0;
        var y_MoKo = y_Mo - 0;
        var _HTrom_1 = Math.atan(x_MoKo/y_MoKo)*180/Math.PI;
        if (x_Mo <= 0 && y_Mo >= 0){
            var _HTrom_2 = 180 - _HTrom_1;
        } else if (x_Mo <= 0 && y_Mo <= 0) {
            var _HTrom_2 = 360-_HTrom_1;
        } else if (x_Mo >= 0 && y_Mo <= 0) {
            var _HTrom_2 = -_HTrom_1;
        } else if (x_Mo >= 0 && y_Mo >= 0) {
            var _HTrom_2 = 180 -_HTrom_1;
        }
        var lamtron_HTrom_2 = parseFloat(_HTrom_2); var _HTrom = Math.round(lamtron_HTrom_2 * 10)/10;
        var _Srom = _D;
        ctx.translate(x_a,y_a);
        var x_trunggian= radius*Math.sin(_HTrom_1*Math.PI/180);
        var y_trunggian= radius*Math.cos(_HTrom_1*Math.PI/180);
        if (y_MoKo>0){
        ctx.beginPath();
        ctx.strokeStyle='black';
        ctx.moveTo(0,0);
        ctx.lineTo(-x_trunggian,-y_trunggian);
        ctx.lineWidth= 1;
        ctx.stroke();
        ctx.translate(-x_a,-y_a);
        } else{
            ctx.beginPath();
            ctx.strokeStyle='black';
            ctx.moveTo(0,0);
            ctx.lineTo(x_trunggian,y_trunggian);
            ctx.lineWidth= 1;
            ctx.stroke();
            ctx.translate(-x_a,-y_a);
        }
        var x_Vrom = 0 - x_Mo;
        var y_Vrom = 0 - y_Mo;
        var x_a_doi = x_a/heso_kc;
        var y_a_doi = y_a/heso_kc;
            if (x_Vrom == 0){
               var x_b = x_a;
               var y_b1 = Math.sqrt(Math.pow(_Vtk_doi*10,2)-Math.pow(x_a_doi,2));
               var y_b2 = -Math.sqrt(Math.pow(_Vtk_doi*10,2)-Math.pow(x_a_doi,2)); 
               if (y_b1/y_Mo <0){
                   var y_b = y_b1*heso_kc;
               } else {
                   var y_b = y_b2*heso_kc;
               }
            } else {
            var d1 = (x_Vrom*y_a_doi - y_Vrom*x_a_doi)/x_Vrom;
            var a1 = 1 + Math.pow(y_Vrom/x_Vrom,2);
            var b1 = 2*(y_Vrom/x_Vrom)*d1;
            var c1 = Math.pow(d1,2) - Math.pow(_Vtk_doi*10,2);
            var delta1 = b1*b1 - 4*a1*c1;
            var x_b1 = (-b1 + Math.sqrt(delta1))/(2*a1);
            var x_b2 = (-b1 - Math.sqrt(delta1))/(2*a1);
            if ((x_b1/1-x_a_doi/1)/x_Vrom > 0){
                var x_b_1 = x_b1;
            } else {
                var x_b_1 = x_b2;
            }
            var x_b = x_b_1*heso_kc;
            var y_b = ((y_Vrom/x_Vrom)*x_b_1 + d1)*heso_kc;
            }
            ctx.beginPath();
            ctx.strokeStyle = 'red';
            ctx.arc(x_b, y_b, 3, 0, 2*Math.PI);
            ctx.stroke();
        var x_ab = x_b - x_a;
        var y_ab = y_b - y_a;
        var _Vrom_1 = Math.sqrt(Math.pow(x_ab,2)+Math.pow(y_ab,2))/heso_v;
        var lamtron_Vrom_1 = parseFloat(_Vrom_1); var _Vrom = Math.round(lamtron_Vrom_1 * 10)/10;
        var x_Kob= x_b - 0;
        var y_Kob = y_b - 0;
        var _HTm_1 = Math.atan(x_Kob/y_Kob)*180/Math.PI;
        if (0 <= x_b && 0 >= y_b){
            var _HTm_2 = 180 - _HTm_1;
        } else if (0 <= x_b && 0 <= y_b) {
            var _HTm_2 = 360 -_HTm_1;
        } else if (0 >= x_b && 0 <= y_b) {
            var _HTm_2 = -_HTm_1;
        } else if (0 >= x_b && 0 >= y_b) {
            var _HTm_2 = 180 -_HTm_1;
        }
        var lamtron_HTm_2 = parseFloat(_HTm_2); var _HTm = Math.round(lamtron_HTm_2 * 10)/10;
        var x_HTm = -radius*Math.sin(_HTm_2*Math.PI/180);
        var y_HTm = radius*Math.cos(_HTm_2*Math.PI/180)
        ctx.beginPath();
        ctx.strokeStyle = 'red';
        ctx.moveTo(0,0);
        ctx.lineTo(x_HTm,y_HTm);
        ctx.lineWidth= 1;
        ctx.stroke();
        var tm_1 = _Srom/_Vrom_1;
        var lamtron_tm_1 = parseFloat(tm_1); var tm = Math.round(lamtron_tm_1 * 10)/10;
        ctx.rotate(-Math.PI);
        ctx.font = 'bold 11pt UTM Avo';
        ctx.fillStyle = 'blue';
        ctx.fillText ('a',-x_a-7,-y_a-7);
        ctx.fillText ('Ko', 5, 15);
        ctx.fillStyle = 'red';
        ctx.fillText ('Mo',-x_Mo+8,-y_Mo+8);
        ctx.fillText ('b',-x_b-7,-y_b-7);
        ctx.fillStyle = 'black';
        ctx.fillText ('HTm',-x_HTm-8,-y_HTm-8);
        ctx.rotate(Math.PI);
        outputText_huongdi= "- Hướng tiếp cận HTm = " + _HTm + " độ.";
        outputText_thoigian= "- Thời gian tiếp cận tm = " + tm + " phút.";
        outputText_HTrom=_HTrom;
        outputText_Srom=_Srom;
        outputText_Vrom=_Vrom;
        outputText_HTm=_HTm;
        outputText_tm=tm;
        
        document.getElementById("output_text_huongdi").innerHTML = outputText_huongdi;
        document.getElementById("output_text_thoigian").innerHTML = outputText_thoigian;
        document.getElementById("output_text_HTrom").innerHTML = outputText_HTrom;
        document.getElementById("output_text_Srom").innerHTML = outputText_Srom;
        document.getElementById("output_text_Vrom").innerHTML = outputText_Vrom;
        document.getElementById("output_text_HTm").innerHTML = outputText_HTm;
        document.getElementById("output_text_tm").innerHTML = outputText_tm;
    }
}
    

